spacecubics/scsat1-fsw

.github/workflows/build.yaml

Zephyr is a fast moving target.  Even though we don't have any changes in our repo, Zephyr is changing rapidly.  Until we set a target version on this repo, test at least once a day.

.github: workflow: Run the build test every day

---

.github/dependabot.yml

Let Dependabot to check versions of GitHub Actions.

.github: Add Dependabot

---

main/CMakeLists.txt
tests/hwtest/adcs/CMakeLists.txt
tests/hwtest/main/CMakeLists.txt

BOARD_ROOT must be an absolute path but not a "canonical" path. having multiple ".." is stil an absolute path.  Thus, we don't need to use get_filename_component() to get a canonical path.

Simplifiy BOARD_ROOT directory path

---

zephyr/drivers/misc/sc_dstrx3.c

In C, a literal value like `2.5` is considered a `double`. When you multiply a `float` by a `double`, implicit promotion occurs, performing the calculation in 64 bits. This unnecessarily consumes CPU power on MCUs.
```
[116/166] Building C object modules/scsat1-fsw/drivers/misc/CMakeFiles/..__scsat1-fsw__zephyr__drivers__misc.dir/sc_dstrx3.c.obj
In file included from /home/yashi/work/spacecubics/launch2022/scsat1-fsw/workspace/zephyr/include/zephyr/logging/log.h:11,
from /home/yashi/work/spacecubics/launch2022/scsat1-fsw/workspace/scsat1-fsw/zephyr/drivers/misc/sc_dstrx3.c:9:
/home/yashi/work/spacecubics/launch2022/scsat1-fsw/workspace/scsat1-fsw/zephyr/drivers/misc/sc_dstrx3.c: In function 'sc_dstrx3_get_hk_telemetry':
/home/yashi/work/spacecubics/launch2022/scsat1-fsw/workspace/scsat1-fs …
```

drivers: dstrx3: Fix implicit conversion from float to double

---

.github/workflows/build.yaml

By using zephyrproject-rtos/action-zephyr-setup, we can simplify our build test.

.github: workflow: Simplify the build test

---

bootloader/CMakeLists.txt
bootloader/Kconfig
bootloader/app.overlay
bootloader/prj.conf
bootloader/src/main.c
bootloader/src/qspi_norflash.c
bootloader/src/qspi_norflash.h

This commit adds a simple bootloader.
This simple bootloader directly accesses the registers of the FPGA SPI Core without using the SPI driver in Zephyr.
These code is based on the code from the PDI repository.
All settings such as the address of the config memory where the Zephyr application is stored and the size to be copied need to be configured in Kconfig.

bootloader: Add simple bootloader

---

boards/arm/scsat1_adcs/scsat1_adcs.dts
boards/arm/scsat1_main/scsat1_main.dts
zephyr/drivers/can/can_sccan.c

In the Zephyr CAN common driver, automatic calculation of SJW was already implemented below commit.
- e397b85 drivers: can: calculate a default SJW value
Therefore, deprecated SJW settings were removed commit below, and this commit also removes from the SC CAN driver.
- 0c13f38 dts: bindings: can: remove deprecated properties for initial timing

boards,zephyr/driver/can: Remove sjw in dts

---

tests/hwtest/tools/parse_main.py

- Summary
This change is to read the HK telemetry data of DSTRX-3 and output it as CSV files or PDF files. This was added because DSTRX-3 is connected to the Main OBC and can now read data.
- Scope of impact
The impact of this change is the addition of outputting CSV files recording DSTRX-3's HK telemetry and adding some graphs to the PDF files.
- Notice
The added part follows the descriptions of other components, but it looks different from other descriptions because DSTRX's telemetry data contains a fixed number of spaces, so the same number of spaces is added to avoid changes in the control code section.

hwtest/tools: Add DSTRX-3 parameters to be parsed

---

tests/hwtest/tools/parse_main.py

This commit fixes the log pareser for MAIN HW test.
- Add `IO_VDD_3V3 Bus`
- Change ohm for `IO_PDU_04_3V3 Shunt` due to hw tuning

hwtest/tools: Fix main log parser for HW test

---

tests/hwtest/adcs/src/main.c
tests/hwtest/main/src/main.c

This commit change the default test from `loop` to `syshk` on auto run test.

hwtest/main,adcs: Change default test on auto run

---

tests/hwtest/main/src/syshk_test.c

When running the test in test mode 0 (MAIN Board only), it will detect errors in the CSP related to ADCS/PYLOD, which should not have been conducted.
This is because the initialization of the test result structure has not been performed, so all result fields are initialized to 0.

hwtest/main: Fix the erroneous error detected in test mode 0

---

tests/hwtest/adcs/src/common.h
tests/hwtest/adcs/src/main.c
tests/hwtest/main/src/common.h
tests/hwtest/main/src/main.c

This commit fixes an issue where the loop test would unexpectedly stop, such as when the stop command is executed twice.

hwtest/main,adcs: Fix unexpected stop on loop test

---

adcs/CMakeLists.txt
drivers/misc/CMakeLists.txt

This commit fixes the board name for SC-Sat1 ADCS.

Fix board name

---

boards/sc/scsat1_adcs/scsat1_adcs.dts
boards/sc/scsat1_main/scsat1_main.dts

This commit is related to ad96a126a. According to the change from 'bus-speed' to 'bitrate,' the property in the DTS will also be renamed.

dts: Rename bus-speed property for CAN driver

---

drivers/misc/dstrx3/sc_dstrx3.c
drivers/misc/dstrx3/sc_dstrx3.h
tests/hwtest/main/src/main_init.c
tests/hwtest/main/src/pwrctrl.c
tests/hwtest/main/src/pwrctrl.h

This PR fixes the device initialization on DSTRX-3 driver.

Fix device init on dstrx3 driver

---

.github/workflows/build.yaml

Zephyr 3.7 LTS requires Python 3.10 or higher. Therefore, building with Python 3.9 is no longer supported. This commit removes Python 3.9 from the build targets to reflect this requirement.
Note: Ubuntu 20.04 ships with Python 3.8, which also doesn't meet Zephyr's minimum Python version requirement. Users on Ubuntu 20.04 will need to install Python 3.10 or newer manually to build Zephyr 3.7 LTS.

github/workflow: Remove Python 3.9 support

---

tests/hwtest/main/src/syshk_test.c
tests/hwtest/main/src/version.h

This commit fixes the destination port for ADCS telemetry via MAIN board.

Fix csp port number for adcs syshk

---

drivers/spi/CMakeLists.txt

When building a zephyr sample that does not use the SPI driver, the following error occurs.
CMake Error at xxx (target_include_directories):
Cannot specify include directories for target "drivers__spi" which is not
built by this project.
This commit removes this error.

drivers/spi: "Remove build error when SPI is not used

---

drivers/misc/fpga/sc_fpgasys.c
drivers/misc/fpga/sc_fpgasys.h
tests/hwtest/adcs/src/main.c
tests/hwtest/adcs/src/sysmon.c
tests/hwtest/adcs/src/sysmon.h
tests/hwtest/main/src/main.c
tests/hwtest/main/src/sysmon.c
tests/hwtest/main/src/sysmon.h

This commit moves the API for retrieving information from the FPGA System Register to the already implemented FPGA sys driver.

drivers/misc/fpga: Move system register API from hwtest

---

lib/flash/data_nor.c

This commit enables a custom log level for the library related to data store flash.

lib/flash: Enable custom log level

---

adcs/Kconfig
adcs/src/csp.c
main/Kconfig
main/src/csp.c

Previously, the CSP router/server thread settings were defined in source code, but this commit changes it to allow configuration via Kconfig.

main,adcs: Change to use Kconfig for CSP thread

---

adcs/src/cmd/tlm.c
main/src/cmd/tlm.c

When a one-shot request for system HK telemetry, the reply telemetry, which includes an error code, is also downlinked along with the system HK telemetry. This is because a reply intended for an abnormal
command code is mistakenly sent. This commit fixes the issue.

main,adcs: Fix unexpected reply telemetry

---

adcs/src/cmd/handler.c
adcs/src/cmd/handler.h
adcs/src/mon/system.c
lib/csp/sys.c
lib/csp/sys.h
main/src/cmd/handler.c
main/src/cmd/handler.h
main/src/mon/system.c

Currently, the CSP command received counter does not specifically check the source, so monitoring pings periodically sent from the EPS are being included in the count. in this commit, it is limit to CSP commands from the Ground only.

CSP counter limit to ground command

---

lib/csp/flash.c
lib/flash/data_nor.c
lib/flash/data_nor.h

This commit adds an erase API for the NOR flash partition used for data storage. The NOR flash for data storage has two banks, but currently, only one bank is usable. Therefore, Erase will only support the bank in use.

Add erase data nor command

---

lib/csp/file.c

Fixes an issue where the received CSP packet was not being released when the file operation workqueue is busy.

lib: csp: Fix release leak when file operation

---

adcs/src/mon/cv.c
adcs/src/mon/cv.h
adcs/src/tlm/syshk.c

The 12V VDD will not be used in our initial operations, and the 3V3 DRV, which serves as the power supply for the CV monitor we monitor, will also not be enabled. Therefore, it will be removed from the System HK during the initial operations.

adcs: Remove VDD 12V CV for ADCS System HK

---

adcs/src/main.c
lib/flash/config_nor.c
lib/flash/config_nor.h
main/src/main.c

SC-Sat1 has two Configuration NOR flash memory banks (bank0/bank1). Normally, FPGA configuration is performed from bank0, and the FSW (Flight Software) also boots from the same bank.
However, when an FSW booted from bank0 executes operations such as erasing NOR flash on bank1, the device appears to ignore the erase command.
This issue occurs because the NOR flash used in SC-Sat1 has a capacity of 32MB, requiring the 4-byte address access mode to be configured on the NOR flash. However, this mode is not set for the NOR flash on the bank1 side.
The 4-byte address mode is set only during the initialization of the spi-nor driver. When the FSW is booted from bank0, the NOR flash on the disconnected bank1 side does not have this setting applied.
As a workaround for this issue, this commit …

lib/flash: Workaround of Config NOR bank1 issue

---

lib/csp/CMakeLists.txt
lib/csp/Kconfig

Currently, during File Upload, we have faced that when data packets are missing, and LittleFS attempts to write data to an offset larger than the current file size, a process is triggered to copy previously written block data to a new block. This copying process can take up to about 7 seconds.
During this time, CSP packets accumulate in the libcsp buffer without being released, causing the application to stuck. We will investigate the root cause of the stucking issue further, but as a workaround, we will increase the FIFO-related settings in libcsp and th eapplication's work queue size.
These values are provisional for testing purposes. However, even with this commit applied, memory usage remains at around 11%.

lib/csp: Increase parameters for File Upload feature

---

lib/csp/sys.c
lib/csp/sys.h

This commit adds a command to read the address of an arbitrary FPGA register and return the value to the ground.

lib/csp: Add Read FPGA register command

---

lib/csp/upload.c

Fixes a missing conversion process to little-endian for the session ID in the reply telemetry of the file upload.

lib/csp: Fix missing endian convert

---

west.yml

We will lock the revisions of Zephyr, libcsp, and littlefs for the first release of SC-Sat1 FM. These revisions correspond to the versions that were applied during the operational tests of the FM.

west.yml: Lock revision

---

lib/csp/flash.c

Fix an issue where the command argument offset for FLASH_CFG_ERASE_CMD was incorrect with commit below.
commit cbded7b611ff01e6c6c933ae3da34b4265584cd6
Author: Takuya Sasaki <takuya.sasaki@spacecubics.com>
Date:   Sat Nov 23 21:05:53 2024 +0900
lib/csp: Add FRAM save option to Config Memory CRC

lib/csp: Fix argument offset for Config Memory operations

---

lib/csp/flash.c

After saving the CRC calculation result of the Config Memory to FRAM, read it back. However, this was for debugging purposes, so remove it.

lib/csp: Remove unnecessary FRAM read

---

lib/csp/CMakeLists.txt
lib/csp/Kconfig

The parameter increased in the following commit will be changed to 300 to help reduce the increase in binary size.
commit 9ba78c8
lib/csp: Increase parameters for File Upload feature

lib/csp: Tune parameter for File Upload feature

---

adcs/src/version.h
lib/core/pwrctrl_adcs.c

Fixes an issue where disabling the power control for ADCS was not working correctly. This issue had been resolved on the MAIN board in the following commit but had not been deployed to ADCS.
commit https://github.com/spacecubics/scsat1-fsw/commit/f97719a85d901e016e08d062a84f7cfa339af8b0
hwtest/main: Fix Power disable not working

Fix power disable for adcs

---

lib/fram/fram.c

Correct typo in function name verify_status_resisger1 → verify_status_register1.
The function name contained a typo ("resisger" instead of "register").
No functional change.

lib: fram: Fix typo in function name verify_status_resisger1
